name: Update Game URL

# Run every Thursday at 05:00 and 07:00 UTC
on:
  schedule:
    - cron: '0 5 * * 4'
    - cron: '0 7 * * 4'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-game-url:
    environment: "GitHub Action"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping dependency installation."
          fi

      - name: Run getApkData.py
        run: python getApkData.py

      - name: Set executable permissions for Il2CppDumper
        run: chmod +x ./extracted/Il2CppDumper/Il2CppDumper

      - name: Run getJPVersion.py
        run: python getJPVersion.py

      - name: Extract commit message from config.json
        id: extract
        run: |
          # Use jq to extract the ServerInfoDataUrl from config.json
          url=$(jq -r '.ServerInfoDataUrl' config.json)
          echo "URL: $url"
          # Extract the commit message from the URL (string between the last "/" and ".json")
          commit_msg=$(echo "$url" | sed -n 's#.*/\([^/]*\)\.json#\1#p')
          echo "Commit message: $commit_msg"
          echo "commit_msg=$commit_msg" >> $GITHUB_OUTPUT

      - name: Check if config.json changed
        id: check_diff
        run: |
          # Configure git so that commit actions work
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          # Check if config.json exists on the main branch
          if git ls-tree -r origin/main --name-only | grep -q "^config.json$"; then
            echo "config.json exists on main branch."
            # Compare the current config.json with the one on origin/main
            if git diff origin/main -- config.json --quiet; then
              echo "No changes in config.json, exiting."
              echo "changed=false" >> $GITHUB_OUTPUT
            else
              echo "Changes detected in config.json."
              echo "changed=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "config.json does not exist on main branch, treating as change."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Send update to Discord and push changes
        if: steps.check_diff.outputs.changed == 'true'
        run: |
          # Extract game_url from ServerInfoDataUrl and latest catalog URL from OverrideConnectionGroups in config.json
          game_url=$(jq -r '.ServerInfoDataUrl' config.json)
          catalog=$(jq -r '.ConnectionGroups[0].OverrideConnectionGroups | .[-1].AddressablesCatalogUrlRoot' config.json)
          
          # Construct the commit message as {game_url}_{catalog} and remove protocol for readability
          commit_msg="${game_url}_${catalog}"
          commit_msg=$(echo "$commit_msg" | sed -E 's#https?://##g')

          # Add and commit config.json with the commit message
          git add config.json
          git commit -m "$commit_msg"
          
          # Capture the commit hash and construct the commit URL
          commit_hash=$(git rev-parse HEAD)
          commit_url="https://github.com/${GITHUB_REPOSITORY}/commit/${commit_hash}"
          
          # Push the commit to main
          git push origin HEAD:main
          
          # Pretty print config.json content using jq
          config_content=$(jq '.' config.json)
          
          # Get the current UTC timestamp in ISO 8601 format
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          
          # Create the embed description with commit details and config data
          embed_description="**Commit URL:** [${commit_url}](${commit_url})\n\n**Config Data:**\n\`\`\`json\n${config_content}\n\`\`\`"
          
          # Create the JSON payload for the Discord webhook using jq
          payload=$(jq -n \
            --arg title "Config Update" \
            --arg description "$embed_description" \
            --arg url "$commit_url" \
            --arg timestamp "$timestamp" \
            '{
              embeds: [
                {
                  title: $title,
                  description: $description,
                  url: $url,
                  color: 255,
                  timestamp: $timestamp
                }
              ]
            }')
          
          # Send the embed payload to Discord
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$payload" \
               "${{ secrets.DISCORD_WEBHOOK_URL }}"
