name: Update Game URL

on:
  schedule:
    # Run every Wednesday at 03:00, 05:00, and 07:00 UTC
    - cron: '0 3 * * 3'
    - cron: '0 5 * * 3'
    - cron: '0 7 * * 3'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-game-url:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping dependency installation."
          fi

      - name: Run getApkData.py
        run: python getApkData.py

      - name: Set executable permissions for Il2CppDumper
        run: chmod +x ./extracted/Il2CppDumper/Il2CppDumper

      - name: Run getJPVersion.py
        run: python getJPVersion.py

      - name: Check if config.json changed
        id: check_diff
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          if ! git diff --quiet origin/main -- data/config.json; then
            echo "Changes detected in data/config.json (or file is new/untracked)."
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in data/config.json."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Config Update
        if: steps.check_diff.outputs.changed == 'true'
        run: |
          echo "Attempting to commit and push changes..."
          # Extract data for commit message using jq and sed
          raw_game_url=$(jq -r '.ServerInfoDataUrl' data/config.json)
          raw_catalog=$(jq -r '.ConnectionGroups[0].OverrideConnectionGroups | .[-1].AddressablesCatalogUrlRoot' data/config.json)

          # Extract the part between the last "/" and ".json"
          game_url=$(echo "$raw_game_url" | sed -n 's#.*/\([^/]*\)\.json#\1#p')
          # Extract the part after the last "/"
          catalog=$(echo "$raw_catalog" | sed -n 's#.*/\([^/]*\)$#\1#p')

          # Construct commit message
          commit_msg="${game_url}_${catalog}"
          echo "Commit message: $commit_msg"

          # Add the files that should be committed
          git add data/config.json data/dump.cs data/BlueArchive.fbs

          # Commit the changes
          git commit -m "$commit_msg"

          # Push the commit to the main branch
          git push origin HEAD:main
          echo "Changes pushed successfully."

      - name: Send update to Discord
        if: steps.check_diff.outputs.changed == 'true'
        env:
           DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          commit_hash=$(git rev-parse HEAD)
          commit_url="https://github.com/${GITHUB_REPOSITORY}/commit/${commit_hash}"

          dump_data_link="https://github.com/${GITHUB_REPOSITORY}/raw/${commit_hash}/data/dump.cs"
          fbs_data_link="https://github.com/${GITHUB_REPOSITORY}/raw/${commit_hash}/data/BlueArchive.fbs"
          config_link="https://github.com/${GITHUB_REPOSITORY}/raw/${commit_hash}/data/config.json"

          raw_game_url=$(jq -r '.ServerInfoDataUrl' data/config.json)
          game_url=$(echo "$raw_game_url" | sed -n 's#.*/\([^/]*\)\.json#\1#p')

          catalog_version=$(jq -r '.ConnectionGroups[0].OverrideConnectionGroups | .[-1].Name' data/config.json)
          raw_catalog=$(jq -r '.ConnectionGroups[0].OverrideConnectionGroups | .[-1].AddressablesCatalogUrlRoot' data/config.json)
          catalog=$(echo "$raw_catalog" | sed -n 's#.*/\([^/]*\)$#\1#p')

          embed_description=$(cat <<EOF
          **Game Info**
          Server Info Data Url: [(${game_url})](${raw_game_url})
          Catalog Version: ${catalog_version}
          Catalog Url: ${catalog}

          **Game Data**
          Dump Data: [dump.cs](${dump_data_link})
          FBS Data: [BlueArchive.fbs](${fbs_data_link})
          Config Data: [config.json](${config_link})
          EOF
          )

          # Get current UTC timestamp
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # Create JSON payload for Discord using jq
          # Using --arg ensures proper JSON string escaping
          payload=$(jq -n \
            --arg title "JP Config Update" \
            --arg description "$embed_description" \
            --arg url "$commit_url" \
            --arg timestamp "$timestamp" \
            '{
              "embeds": [
                {
                  "title": $title,
                  "description": $description,
                  "url": $url,
                  "color": 255,
                  "timestamp": $timestamp
                }
              ]
            }')

          # Send the payload to Discord using curl
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$payload" \
               "$DISCORD_WEBHOOK_URL"
          echo "Discord notification sent."